### ISSUE TITLE
Messages sent in DM between invitation and invitation acceptation aren't accessible 

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android#649]
"Bug: sur Android cela fait deux personnes qui débutent un chat privé avec moi dont les messages ne s'affichent pas, même après avoir accepté la conversation. Obligé de demander un renvoi des messages"

Julien : I also got this trouble

**Comment by jdauphant** [comment]
Problem : 
- Toto sent me an invitation for a DM
- Toto sent me a message for I accept the invitation
- I accept the invitation, I don't see the message of Toto, I see that :
![image](https://user-images.githubusercontent.com/1238254/175126685-7a71bcb7-14d2-44b5-9d35-758b8aeb9e56.png)
- If I clear cache, I got this : 
![image](https://user-images.githubusercontent.com/1238254/175126986-f6216a56-166c-47cf-9a71-3ef8505f88ea.png)

**Comment by giomfo** [comment]
@Claire1817 can you please try to reproduce this issue in Element-Android with the version related to our last rebase, and the most recent version of Element?

**Comment by Claire1817** [comment]
Tests:
On version 2.3.1: 
- Between 2 Android emulator, bug reproduced each time.
- Between a web client and android emulator (and android emulator and web client), bug not reproduced
On develop:
- Between 2 Android emulator, bug reproduced each time.
- Between a web client and android emulator (and android emulator and web client), bug not reproduced

**Comment by jdauphant** [comment]
You mean develop on Element or Tchap ?

**Comment by Claire1817** [comment]
I did the test on Element:
On element tag v1.4.16 (current version used in tchap develop): bug not reproduced
On element develop branch: bug not reproduced

**Comment by giomfo** [comment]
@Claire1817 during your tests on Tchap, did you use 2 accounts hosted on the same server? It may be a difference with your test on Element

**Comment by Claire1817** [comment]
Tchap: after a test with 2 accounts hosted on the same server i didn't reproduce the bug with 2 android application and on web application and one android application.

**Comment by giomfo** [comment]
@Claire1817 I let you compare the logs between Web and Android clients.  Some client-server requests trigerred by the client when you joined the invited room may be different.
I think Android is missing an initial sync (which may be required in case of federated room)

**Comment by Claire1817** [comment]
Update:
Tests with Element application (develop branch) with tchap serveur, it's working with no problem.
I will do a rebase against element 1.4.27 and i will test it after: the problem is maybe solved and if not we will use flipper to debug.

**Comment by jdauphant** [comment]
@giomfo is this fixed with the last release ?

**Comment by giomfo** [comment]
> @giomfo is this fixed with the last release ?

no, we will test again when the rebase v1.4.27 will be merged, but for the moment this is not fixed
